### ISSUE TITLE
Please add a timezone picker to the datetime component

### ISSUE THREAD

**Issue by calebmeyer** [cerner/terra-framework#782] opened 2019-07-11 21:23 UTC
# Feature Request

## Description
The [date time picker](https://engineering.cerner.com/terra-ui/#/components/terra-date-time-picker/date-time-picker/date-time-picker) component does not include anything related to time zones. For multi-tenant deployments, you cannot assume that all tenants will belong to a single time zone. I'd like to see a dropdown that's populated with all the timezone names, like `America/Chicago`

## Additional Context / Screenshots
We are currently uplifting healtheanalytics to terra. One of the components that our older style guide, blue steel, had was a datetime picker with timezone. It looks like this:
![image](https://user-images.githubusercontent.com/3342777/61086264-04d81e00-a3f8-11e9-96b4-cfe3e58f7e73.png)

If we want to update to the terra version, we'd today have to create our own select box and populate it ourselves. Since this will probably be a common ask, I think it makes sense to add to terra.

## @ Mentions
@bjankord asked me to log this, so I guess him

**Comment by bjankord** [comment] 2019-07-11 21:26
Is the timezone picker needed for date time picking or purely time picking? It looks like the in the screenshot it is for available for just the time picker?

**Comment by calebmeyer** [comment] 2019-07-11 21:27
We're currently using it alongside both date and time to implement scheduling. Blue steel supports any combination of the three.

**Comment by bjankord** [comment] 2019-07-24 14:38
Related: https://github.com/cerner/terra-framework/issues/457

**Comment by benbcai** [comment] 2019-10-30 16:02
Closing this as a duplicate of #457

**Closed by benbcai** 2019-10-30 16:02 UTC
Labels: Needs Design Input, Needs Orion Requirements, Orion Reviewed, priority:low
