### ISSUE TITLE
[terra-date-picker] Red border is missing from invalid date-time inputs in fusion theme

### ISSUE THREAD

**Issue by saket2403** [cerner/terra-framework#1413] opened 2021-05-20 05:47 UTC
# Bug Report

## Description
A red border is applied to invalid date time inputs in default theme. But no red border is applied in fusion theme . Consumers want same styles in both themes. The issue is in all the 4 date-time components.
## Steps to Reproduce

1. Change theme to orion-fusion in dev site 
2. Check invalid date picker example [here](https://engineering.cerner.com/terra-ui/components/terra-date-picker/date-picker/date-picker).

## Additional Context / Screenshots
Missing Red color
<img width="169" alt="Screenshot 2021-05-20 at 11 11 07 AM" src="https://user-images.githubusercontent.com/42207428/118925308-22fbf700-b95c-11eb-93f2-3000b246ce35.png">

## Expected Behavior

A red border should be applied

## Possible Solution
Change the color [here](https://github.com/cerner/terra-framework/blob/main/packages/terra-date-picker/src/orion-fusion-theme/DatePicker.module.scss#L15-L19)

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@ryanthemanuel @benbcai @neilpfeiffer

**Comment by neilpfeiffer** [comment] 2021-05-20 14:18
@saket2403 Please see the comment on [terra-core/issues/3427](https://github.com/cerner/terra-core/issues/3427#issuecomment-830158015) which gives the explanation as to why the `orion-fusion-theme` intentionally does not have red borders on the form elements when they are set to `isInvalid` by design.

Will close as duplicate and won't fix unless there are any additional concerns.

**Comment by ryanthemanuel** [comment] 2021-05-24 14:07
Closing per @neilpfeiffer's comments.

**Closed** 2021-05-24 14:06 UTC
Labels: :package: terra-date-input, :package: terra-date-picker, :package: terra-date-time-picker, :package: terra-time-input, wontfix
