### ISSUE TITLE
Axe Issue "ARIA hidden element must not contain focusable elements" in multiple components

### ISSUE THREAD

**Issue by supreethmr** [cerner/terra-framework#861] opened 2019-08-30 06:00 UTC
# Issue Description
Axe tool Throws up "ARIA hidden element must not contain focusable elements"  issue for 
1. Terra-Modal-Manager
2. Terra-Dialog-modal 
3. Terra-Overlay
4. Terra-Notification-Dialog

# Steps to recreate
1. Navigate to https://engineering.cerner.com/terra-ui/components/terra-modal-manager/modal-manager/about 
2. Open modal dialog in any of the examples 
3. Modal dialog shows up. run Axe tool to see the issues listed for modal-manager
( Same steps for all the other components mentioned above)

## Additional Context / Screenshots
Modal-manager :
![Screen Shot 2019-08-30 at 11 11 28 AM](https://user-images.githubusercontent.com/12869809/63995667-fd3f1680-cb16-11e9-90b7-38d05d218474.png) 

Dialog-Modal : 
![Screen Shot 2019-08-30 at 11 13 59 AM](https://user-images.githubusercontent.com/12869809/63996185-8dca2680-cb18-11e9-96f6-b33102b0af17.png)

Overlay : 
![Screen Shot 2019-08-30 at 11 14 53 AM](https://user-images.githubusercontent.com/12869809/63996208-a3d7e700-cb18-11e9-9aed-c5b9602a235c.png)

Notification-Dialog : 
![Screen Shot 2019-08-30 at 11 15 27 AM](https://user-images.githubusercontent.com/12869809/63996229-b5b98a00-cb18-11e9-90ff-9c4e5b2e12b6.png)

Ion-provider-relationship-js Jenkins  : https://jenkins.cerner.com/ion/blue/organizations/jenkins/ion-server-core%2Fion-provider-relationship-js/detail/dev/65/pipeline/

**Comment by pranav300** [comment] 2019-09-03 10:05
After investigation what i am able to find is that all the violations are caused by `details` tag in the terra-ui as when we are using `inert` on the root element, it removes all tabindex for the child elements and due to which `details` tag gets focusable. @bjankord what do you think about it?


The above user issue has been resolved as it was a version mismatch.

**Comment by supreethmr** [comment] 2019-09-03 11:06
Thank you for investigating @pranav300 😃

**Comment by bjankord** [comment] 2019-09-03 14:36
Nice investigation @pranav300. It seems like this may be something the [inert polyfill](https://github.com/WICG/inert) we are using _should_ handle, however, it doesn't look to be that way. I would be in favor of logging an issue to https://github.com/WICG/inert and provide them a reduced test case, a page with the inert attribute set in it and a nested details element. Then see if we can determine if they are interested in resolving this issue in the polyfill or if we need to resolve it outside of the polyfill in our own codebase.

**Comment by pranav300** [comment] 2019-09-04 06:47
I have logged an issue in `inert` polyfill repo https://github.com/WICG/inert/issues/133.

**Comment by bjankord** [comment] 2019-09-06 20:01
Planning to remove details element from doc site, it doesn't seem their is a way to remove the details element out of tab order.

**Comment by pranav300** [comment] 2019-09-16 06:37
I am closing this issue as it will be resolved in #883.

**Closed by pranav300** 2019-09-16 06:37 UTC
Labels: Needs investigation, Orion Reviewed
