### ISSUE TITLE
[terra-notification-dialog] 'acceptAction' prop marked as required even when given 'primaryAction'

### ISSUE THREAD

**Issue by BenBoersma** [cerner/terra-framework#974] opened 2019-11-20 20:42 UTC
# Bug Report

## Description
If `primaryAction` is given a value and `acceptAction` is not, notification-dialog will throw a prop warning since `acceptAction` is marked as required.

## Steps to Reproduce
```
import React, { useState } from 'react';
import Button from 'terra-button';
import NotificationDialog, { NotificationDialogVariants } from 'terra-notification-dialog';

const clickConfirm = () => {
  console.log('You clicked confirm'); // eslint-disable-line no-console
};

const CompleteNotificationDialog = () => {
  const [isOpen, setIsOpen] = useState(false);

  const handleOpenModal = () => {
    setIsOpen(true);
  };

  const handleCloseModal = () => {
    setIsOpen(false);
  };

  return (
    <>
      <NotificationDialog
        variant={NotificationDialogVariants.ALERT}
        isOpen={isOpen}
        title="Make sure that the title relates directly to the choices."
        startMessage="The Main Instruction is text used to provide more detail or define terminology. Don’t repeat the title verbatim."
        primaryAction={{
          text: 'Confirm',
          onClick: clickConfirm,
        }}
        secondaryAction={{
          text: 'Close',
          onClick: handleCloseModal,
        }}
        buttonOrder="acceptFirst"
        emphasizedAction="accept"
      />
      <Button text="Trigger NotificationDialog" onClick={handleOpenModal} />
    </>
  );
};

export default CompleteNotificationDialog;
```

## Additional Context / Screenshots
Error Message:
> Warning: Failed prop type: The prop `acceptAction` is marked as required in `NotificationDialog`, but its value is `undefined`.

## Expected Behavior
Should not throw a warning, should just accept the `primaryAction` prop as the `acceptAction` prop.

## Environment
- Component Name and Version: terra-notification-dialog v3.18.0
- Browser Name and Version: All browsers.

**Comment by saket2403** [comment] 2019-11-29 06:03
Why are we keeping both `acceptAction` and `primaryAction` props if the latter is marked as deprecated? Is it because we did not wanted this PR #899 to be a breaking change?
cc @BenBoersma

**Comment by mjhenkes** [comment] 2019-12-02 15:27
@saket2403 Yes, we did not want to introduce a breaking change.

**Comment by saket2403** [comment] 2019-12-12 09:24
What is the expected behaviour if both `acceptAction` and `primaryAction` are not provided?

- Throw an error

- Leave a warning or error in console. 
cc @tbiethman  @PaulSolDev

**Closed** 2020-01-07 16:19 UTC
Labels: Orion Reviewed, bug, notification-dialog
