### ISSUE TITLE
Terra Date Time Picker Weird Behavior Of Year Field On Manual Input

### ISSUE THREAD

**Issue by ayanchax** [cerner/terra-framework#1104] opened 2020-05-04 07:10 UTC
# Bug Report

## Description
Date Time Picker shows ambigious year on manually writing the year in the input box provided
https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/date-time-picker

## Steps to Reproduce
1. Consider any terra date time picker component, for our case we used the  "terra-date-time-picker": "^4.34.0" with Time Variant with 12-hour Time format. Visualisation : YYYY-MM-DD HH:MM AM PM
2. Select a valid date picking from the calendar 05/04/2020.
3. Now Write something gibberish on the month and/or day and/or year fields (make it a invalid date)
4. For our case we changed 05/04/2020 to a complete invalid date 35/25/2465664 in one scenario and a ambigious year scenario but with valid day and month 05/04/2465664.

5. Then again tried selecting a good date by choosing from the datepicker, This time again selected the same date 05/04/2020 but the date picker input box reflects it as 05/04/2465. Next tried with another good date from the picker 05/18 but still the same it becomes 05/18/2465. Seems like It retains the last 4 digit of the year field that was written on the manual input and the year combo box up there shifts to 1900 in both cases. On such scenario, It is expected to either change the date to 05/18/1900 or should come back to the recent year 2020.

This is a bug as user can always type in anything and everything in an input box but needs to be over-riden on select of the date picker to my understanding. Please take a look.

## Environment

* Component Name and Version: DateTime Picker
* Browser Name and Version: Chrome, IE
* Node/npm Version: [e.g. Node 8/npm 5] 
 npm: '6.9.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '4',
  nghttp2: '1.33.0',
  node: '8.16.0',
  openssl: '1.0.2r',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.23.2',
  v8: '6.2.414.77',
  zlib: '1.2.11'
* Webpack Version:
* Operating System and version (desktop or mobile): windows/linux

**Comment by supreethmr** [comment] 2020-05-04 14:13
> Then again tried selecting a good date by choosing from the datepicker, This time again selected the same date 05/04/2020 but the date picker input box reflects it as 05/04/2465.

I don't think this is an bug since we don't have defined limit on year value that can be entered ( for example user can enter 2658 has year which is valid year value so it would be invalid in real time scenario if we define max limit for year value to be entered ) so date-time-picker trimming first 4 digit value from the entered value is expected behaviour as trimming the entered value makes it valid for year field. 

>  the year combo box up there shifts to 1900 in both cases
this is happening since the entered value or the formatted year value is not available within the year combo-box list hence it defaults to initial value. this scenario we might need to fix for having same entered year value in combo-box instead of restoring it to initial year value or to current year value.

the same behaviour we can see in react-date-picker as well : https://reactdatepicker.com/ 
where if you enter year value as 2345 year value retains to same value.

**Comment by ayanchax** [comment] 2020-05-04 15:03
I agree what you said @supreethmr  but if you read the recreation step carefully if I write 05/18/2465 as the year it shoots to 1900 at the top which is fine since that's the smallest year available in the list, but in that case the date should to display as 05/18/1900 as I have technically made a selection of a date from 1900 control.

**Comment by ayanchax** [comment] 2020-05-04 15:03
@ryanthemanuel  thank you for marking this as bug.

**Comment by benbcai** [comment] 2020-05-04 15:40
What is happening here is that when you enter a valid date with a 4-digit year that is beyond the year `2100`, since this is technically a valid date it will continue to be set as the internal state of the date. Is we use a date of `05/04/2465` as in the above example, the year of the internal date will now be `2465`. However, the year dropdown in the picker only shows the years from `1900` to `2100`. Any year that is not between `1900` and `2100` cannot be indexed and would default to index 0, which is 1900 as in this case. When you open the picker to select another date, the calendar is still referenced back to the internal date which is on year `2465`. Hence, when you select the 18th day on the calendar, this is really `05/18/2465` instead of `05/18/1900`. 

What’s really going on here is that year in the year dropdown doesn't match the year represented in the internal date. Although it may be uncommon to enter a date beyond 2100, it is still incorrect for the year dropdown to misrepresent the selected date.

This will not be an issue when the date input is split into three separate inputs on #468  since the year input will not allow values beyond the supported year. I think it is worth fixing this issue before #468 is available.

@ayanchax Did you have a valid use case to enter a year beyond 2100 or was it just for experimentation?

**Comment by ayanchax** [comment] 2020-05-05 01:12
@ayanchax Did you have a valid use case to enter a year beyond 2100 or was it just for experimentation? - It was not for experimentation, the tester would do definitely do stress testing on the component and thus the need, and I think if you think it from a user's perspective it makes sense. User can enter aything and everything but the system should respond smartly.What do you reckon? Atleast if the index does not contain a year that is beyond the limits of 1900 and 2100 it should atleast switch to either the index selected on the next try of selecting a valid date. User would then have no chance to complain about this behavior as the index is set to 1900 on a entry beyond 2100 or less than 1900, So in the next attempt when he selects a date from the calendar he should atleast get the date selected with year 1900 or whatever index he shifts in.

**Comment by ayanchax** [comment] 2020-05-05 01:18
@benbcai Thank you for the comment. So, if this is added to the Future Roadmap 2020 Q2 solution by the Terra team, when can we expect this to be available, I would accordingly inform my team about this feature's unavailability and restrict the tester on such a line and ask them if they are to do manual entries on year field, they need to do it  between the range of 1900 and 2100.

For the record reiterating the failing Use Cases : 
03/05/245600006767 Shifts to 03/05/2456 on next calendar pick.
03/05/2456 Shifts to 03/05/2456 on next calendar pick

PS:  we are not going with the custom solution #468.

**Comment by benbcai** [comment] 2020-05-26 14:06
This is being fixed by limiting the year entry from 1900 to 2100 because the year dropdown only contains years between 1900 and 2100. Years before 1900 or after 2100 can still entered but years outside this range will not be accepted as a a valid year. As a result, the full entered date will become invalid.

**Closed** 2020-06-01 18:09 UTC
Labels: :package: terra-date-time-picker, bug
