### ISSUE TITLE
Enable hot keys for Terra Date/Time field

### ISSUE THREAD

**Issue by JC014157** [cerner/terra-framework#996] opened 2019-12-11 18:01 UTC
# Feature Request

## Description
Allow for end users to quickly enter Today and Now with keyboard shortcuts `T` and `N`.  
Allow users to quickly increment and decrement date and time with keyboard shortcuts `+` and `-`.

## Additional Context / Screenshots
These are common short cut keys that are used for date/time controls in PowerChart as well as other Cerner applications. Adding them into Terra will maintain consistency with other existing Win64 and Java applications.

---
## Future Enhancements
Additional keyboard shortcuts to allow for end users to quickly enter keyboard shortcuts for:
first and last day of the year (`Y` and `R`), first and last day of the month (`M` and `H`), first and last day of the week (`W` and `K`), etc.

**Comment by pranav300** [comment] 2020-01-10 19:32
I have some doubts regarding this issue -
1. Should we also enable hot keys even when the calendar is open?
2. And should I also enable hot keys for the new component terra-date-input?

cc / @ryanthemanuel, @BenBoersma

**Comment by benbcai** [comment] 2020-01-10 19:41
@pranav300 We will have a meeting today to review and discuss how to handle this request. We will provide more information later.

**Comment by benbcai** [comment] 2020-01-13 15:14
@pranav300 Our meeting got rescheduled to later this week. I will update you when we have more information.

**Comment by ShettyAkarsh** [comment] 2020-02-17 05:37
@benbcai, Any updates on this issue ?

**Comment by benbcai** [comment] 2020-02-17 15:27
@ShettyAkarsh There are still some ongoing conversations and engaging the human factor team around how this should work in Terra. UX will provide updates once we know more.

**Comment by scottwilmarth** [comment] 2020-03-19 22:37
Providing shortcuts is a great way to provide for disabled users, especially mobility challenged keyboard-only users. The use of "t" for today, "n" for now, and others are standard keyboard shortcuts that are already existing within both clinical and revenue cycle products. Some clinical products use the "Shift +" in addition to the letter, but the best practice would be to not require "Shift" in addition to a letter. While single letter shortcuts should not be used usually, they are perfectly acceptable in this instance because the date-time input would be in focus for the key commands to work. Here are the basic rules for implementing the commands: 1. Must be expected behavior (consistent and predictable - go with what users already use for the letter, but lose the "Shift +"). 2. Must only occur when the input has focus. 3. Must be documented in solution documentation. 
More investigation would be needed to document the current date-time shortcuts across clinical and revenue cycle solutions (possibly consumer as well) and reconciled for final commands.

**Comment by neilpfeiffer** [comment] 2020-03-20 15:41
@pranav300 @benbcai - Before we can address, UX needs to complete an audit and validate
- which quick actions/key command combinations Terra will support
- how shortcuts will need to be internationalized for non-English languages/locales
- any UI faceup/popover adjustments to also access the same quick actions

**Comment by neilpfeiffer** [comment] 2020-05-14 20:02
### Issue Update:
Current: 
- UX audit to gather the variations in consumer requirements for current and past usages is being assigned to @jeremyfuksa and will begin shortly.

Next/Not Started: 
- Assessment of gathered requirements, with design recommendations of how best to solve for enabling quick keyboard-driven interactions, with companion UI elements 
- Establish requirements for how quick actions/hot keys will need to translate for other locales/languages.
- Establish accessibility requirements for how best to implement and expose for all users.

**Comment by at014421** [comment] 2020-08-26 13:44
Hi, is there any update on this?
cc: @JC014157

**Comment by at014421** [comment] 2021-04-22 17:13
Hello! @neilpfeiffer @ryanthemanuel  is there any update on this?  This is a common clinical workflow that we are going to get lots of feedback  on. cc: @JC014157

**Comment by Hexman768** [comment] 2021-10-01 19:57
@neilpfeiffer @ryanthemanuel Is there any update on this issue? This functionality would be really useful to our users, and we had this functionality working in the old java implementation, however now that functionality is current gone. Any feedback would be much appreciated!

**Comment by at014421** [comment] 2021-10-01 20:25
FYI, Looks like this is now being tracked in jira: https://jira2.cerner.com/browse/UXPLATFORM-5460

**Comment by neilpfeiffer** [comment] 2021-12-20 16:28
Partial implementation will first be added with `terra-date-input`: PR https://github.com/cerner/terra-framework/pull/1483

**Comment by neilpfeiffer** [comment] 2022-03-28 23:42
- Partial implementation added with `terra-time-input`: PR https://github.com/cerner/terra-framework/pull/1503
- Partial implementation added with `terra-date-picker`: PR https://github.com/cerner/terra-framework/pull/1507
- Partial implementation added with `terra-date-time-picker`: PR https://github.com/cerner/terra-framework/pull/1520

**Comment by at014421** [comment] 2022-03-29 12:58
> * Partial implementation added with `terra-time-input`: PR [#1503](https://github.com/cerner/terra-framework/pull/1503)
> * Partial implementation added with `terra-date-picker`: PR [#1507](https://github.com/cerner/terra-framework/pull/1507)
> * Partial implementation added with `terra-date-time-picker`: PR [#1520](https://github.com/cerner/terra-framework/pull/1520)

@neilpfeiffer , do consumers of these terra components need to take an update to get this functionality? Or will we inherit it automatically?

**Comment by neilpfeiffer** [comment] 2022-03-29 14:17
@at014421 - These changes will be passive and a minor version release (not a breaking change or major version release), so as long as consumers are currently using the semver caret(^) preceeding their current import version, they do not need to adjust API, simply do a fresh install and you will receive the new version.

**Closed** 2022-03-29 14:16 UTC
Labels: Requirements Needed, :package: terra-time-input, :package: terra-date-time-picker, :package: terra-date-picker, :package: terra-date-input
